/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHermesRouteImport } from './routes/_authenticated/hermes'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedScansRouteImport } from './routes/_authenticated/scans'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVulnerabilitiesRouteImport } from './routes/_authenticated/vulnerabilities'
import { Route as ApiPanelControlRouteImport } from './routes/api/panel/control'
import { Route as ApiPublicHermesActionsRouteImport } from './routes/api/public/hermes/actions'
import { Route as ApiPublicHermesCommandsRouteImport } from './routes/api/public/hermes/commands'
import { Route as ApiPublicHermesFindingsRouteImport } from './routes/api/public/hermes/findings'
import { Route as ApiPublicHermesHeartbeatRouteImport } from './routes/api/public/hermes/heartbeat'
import { Route as ApiPublicHermesIncidentsRouteImport } from './routes/api/public/hermes/incidents'
import { Route as ApiPublicHermesMaintenanceRouteImport } from './routes/api/public/hermes/maintenance'
import { Route as ApiPublicHermesQueueRouteImport } from './routes/api/public/hermes/queue'
import { Route as ApiPublicHermesScansRouteImport } from './routes/api/public/hermes/scans'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHermesRoute = AuthenticatedHermesRouteImport.update({
  id: '/hermes',
  path: '/hermes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScansRoute = AuthenticatedScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVulnerabilitiesRoute =
  AuthenticatedVulnerabilitiesRouteImport.update({
    id: '/vulnerabilities',
    path: '/vulnerabilities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPanelControlRoute = ApiPanelControlRouteImport.update({
  id: '/api/panel/control',
  path: '/api/panel/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHermesActionsRoute = ApiPublicHermesActionsRouteImport.update({
  id: '/api/public/hermes/actions',
  path: '/api/public/hermes/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHermesCommandsRoute = ApiPublicHermesCommandsRouteImport.update({
  id: '/api/public/hermes/commands',
  path: '/api/public/hermes/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHermesFindingsRoute = ApiPublicHermesFindingsRouteImport.update({
  id: '/api/public/hermes/findings',
  path: '/api/public/hermes/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHermesHeartbeatRoute =
  ApiPublicHermesHeartbeatRouteImport.update({
    id: '/api/public/hermes/heartbeat',
    path: '/api/public/hermes/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHermesIncidentsRoute =
  ApiPublicHermesIncidentsRouteImport.update({
    id: '/api/public/hermes/incidents',
    path: '/api/public/hermes/incidents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHermesMaintenanceRoute =
  ApiPublicHermesMaintenanceRouteImport.update({
    id: '/api/public/hermes/maintenance',
    path: '/api/public/hermes/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHermesQueueRoute = ApiPublicHermesQueueRouteImport.update({
  id: '/api/public/hermes/queue',
  path: '/api/public/hermes/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHermesScansRoute = ApiPublicHermesScansRouteImport.update({
  id: '/api/public/hermes/scans',
  path: '/api/public/hermes/scans',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hermes': typeof AuthenticatedHermesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/scans': typeof AuthenticatedScansRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vulnerabilities': typeof AuthenticatedVulnerabilitiesRoute
  '/api/panel/control': typeof ApiPanelControlRoute
  '/api/public/hermes/actions': typeof ApiPublicHermesActionsRoute
  '/api/public/hermes/commands': typeof ApiPublicHermesCommandsRoute
  '/api/public/hermes/findings': typeof ApiPublicHermesFindingsRoute
  '/api/public/hermes/heartbeat': typeof ApiPublicHermesHeartbeatRoute
  '/api/public/hermes/incidents': typeof ApiPublicHermesIncidentsRoute
  '/api/public/hermes/maintenance': typeof ApiPublicHermesMaintenanceRoute
  '/api/public/hermes/queue': typeof ApiPublicHermesQueueRoute
  '/api/public/hermes/scans': typeof ApiPublicHermesScansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hermes': typeof AuthenticatedHermesRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/scans': typeof AuthenticatedScansRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vulnerabilities': typeof AuthenticatedVulnerabilitiesRoute
  '/api/panel/control': typeof ApiPanelControlRoute
  '/api/public/hermes/actions': typeof ApiPublicHermesActionsRoute
  '/api/public/hermes/commands': typeof ApiPublicHermesCommandsRoute
  '/api/public/hermes/findings': typeof ApiPublicHermesFindingsRoute
  '/api/public/hermes/heartbeat': typeof ApiPublicHermesHeartbeatRoute
  '/api/public/hermes/incidents': typeof ApiPublicHermesIncidentsRoute
  '/api/public/hermes/maintenance': typeof ApiPublicHermesMaintenanceRoute
  '/api/public/hermes/queue': typeof ApiPublicHermesQueueRoute
  '/api/public/hermes/scans': typeof ApiPublicHermesScansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hermes': typeof AuthenticatedHermesRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/scans': typeof AuthenticatedScansRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vulnerabilities': typeof AuthenticatedVulnerabilitiesRoute
  '/api/panel/control': typeof ApiPanelControlRoute
  '/api/public/hermes/actions': typeof ApiPublicHermesActionsRoute
  '/api/public/hermes/commands': typeof ApiPublicHermesCommandsRoute
  '/api/public/hermes/findings': typeof ApiPublicHermesFindingsRoute
  '/api/public/hermes/heartbeat': typeof ApiPublicHermesHeartbeatRoute
  '/api/public/hermes/incidents': typeof ApiPublicHermesIncidentsRoute
  '/api/public/hermes/maintenance': typeof ApiPublicHermesMaintenanceRoute
  '/api/public/hermes/queue': typeof ApiPublicHermesQueueRoute
  '/api/public/hermes/scans': typeof ApiPublicHermesScansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/dashboard'
    | '/hermes'
    | '/incidents'
    | '/scans'
    | '/users'
    | '/vulnerabilities'
    | '/api/panel/control'
    | '/api/public/hermes/actions'
    | '/api/public/hermes/commands'
    | '/api/public/hermes/findings'
    | '/api/public/hermes/heartbeat'
    | '/api/public/hermes/incidents'
    | '/api/public/hermes/maintenance'
    | '/api/public/hermes/queue'
    | '/api/public/hermes/scans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/assets'
    | '/audit'
    | '/dashboard'
    | '/hermes'
    | '/incidents'
    | '/scans'
    | '/users'
    | '/vulnerabilities'
    | '/api/panel/control'
    | '/api/public/hermes/actions'
    | '/api/public/hermes/commands'
    | '/api/public/hermes/findings'
    | '/api/public/hermes/heartbeat'
    | '/api/public/hermes/incidents'
    | '/api/public/hermes/maintenance'
    | '/api/public/hermes/queue'
    | '/api/public/hermes/scans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/assets'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/hermes'
    | '/_authenticated/incidents'
    | '/_authenticated/scans'
    | '/_authenticated/users'
    | '/_authenticated/vulnerabilities'
    | '/api/panel/control'
    | '/api/public/hermes/actions'
    | '/api/public/hermes/commands'
    | '/api/public/hermes/findings'
    | '/api/public/hermes/heartbeat'
    | '/api/public/hermes/incidents'
    | '/api/public/hermes/maintenance'
    | '/api/public/hermes/queue'
    | '/api/public/hermes/scans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPanelControlRoute: typeof ApiPanelControlRoute
  ApiPublicHermesActionsRoute: typeof ApiPublicHermesActionsRoute
  ApiPublicHermesCommandsRoute: typeof ApiPublicHermesCommandsRoute
  ApiPublicHermesFindingsRoute: typeof ApiPublicHermesFindingsRoute
  ApiPublicHermesHeartbeatRoute: typeof ApiPublicHermesHeartbeatRoute
  ApiPublicHermesIncidentsRoute: typeof ApiPublicHermesIncidentsRoute
  ApiPublicHermesMaintenanceRoute: typeof ApiPublicHermesMaintenanceRoute
  ApiPublicHermesQueueRoute: typeof ApiPublicHermesQueueRoute
  ApiPublicHermesScansRoute: typeof ApiPublicHermesScansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hermes': {
      id: '/_authenticated/hermes'
      path: '/hermes'
      fullPath: '/hermes'
      preLoaderRoute: typeof AuthenticatedHermesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scans': {
      id: '/_authenticated/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof AuthenticatedScansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vulnerabilities': {
      id: '/_authenticated/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof AuthenticatedVulnerabilitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/panel/control': {
      id: '/api/panel/control'
      path: '/api/panel/control'
      fullPath: '/api/panel/control'
      preLoaderRoute: typeof ApiPanelControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/actions': {
      id: '/api/public/hermes/actions'
      path: '/api/public/hermes/actions'
      fullPath: '/api/public/hermes/actions'
      preLoaderRoute: typeof ApiPublicHermesActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/commands': {
      id: '/api/public/hermes/commands'
      path: '/api/public/hermes/commands'
      fullPath: '/api/public/hermes/commands'
      preLoaderRoute: typeof ApiPublicHermesCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/findings': {
      id: '/api/public/hermes/findings'
      path: '/api/public/hermes/findings'
      fullPath: '/api/public/hermes/findings'
      preLoaderRoute: typeof ApiPublicHermesFindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/heartbeat': {
      id: '/api/public/hermes/heartbeat'
      path: '/api/public/hermes/heartbeat'
      fullPath: '/api/public/hermes/heartbeat'
      preLoaderRoute: typeof ApiPublicHermesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/incidents': {
      id: '/api/public/hermes/incidents'
      path: '/api/public/hermes/incidents'
      fullPath: '/api/public/hermes/incidents'
      preLoaderRoute: typeof ApiPublicHermesIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/maintenance': {
      id: '/api/public/hermes/maintenance'
      path: '/api/public/hermes/maintenance'
      fullPath: '/api/public/hermes/maintenance'
      preLoaderRoute: typeof ApiPublicHermesMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/queue': {
      id: '/api/public/hermes/queue'
      path: '/api/public/hermes/queue'
      fullPath: '/api/public/hermes/queue'
      preLoaderRoute: typeof ApiPublicHermesQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hermes/scans': {
      id: '/api/public/hermes/scans'
      path: '/api/public/hermes/scans'
      fullPath: '/api/public/hermes/scans'
      preLoaderRoute: typeof ApiPublicHermesScansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHermesRoute: typeof AuthenticatedHermesRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedScansRoute: typeof AuthenticatedScansRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVulnerabilitiesRoute: typeof AuthenticatedVulnerabilitiesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHermesRoute: AuthenticatedHermesRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedScansRoute: AuthenticatedScansRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVulnerabilitiesRoute: AuthenticatedVulnerabilitiesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPanelControlRoute: ApiPanelControlRoute,
  ApiPublicHermesActionsRoute: ApiPublicHermesActionsRoute,
  ApiPublicHermesCommandsRoute: ApiPublicHermesCommandsRoute,
  ApiPublicHermesFindingsRoute: ApiPublicHermesFindingsRoute,
  ApiPublicHermesHeartbeatRoute: ApiPublicHermesHeartbeatRoute,
  ApiPublicHermesIncidentsRoute: ApiPublicHermesIncidentsRoute,
  ApiPublicHermesMaintenanceRoute: ApiPublicHermesMaintenanceRoute,
  ApiPublicHermesQueueRoute: ApiPublicHermesQueueRoute,
  ApiPublicHermesScansRoute: ApiPublicHermesScansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
